# Generated by Django 4.2.19 on 2025-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="join_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
