# Generated by Django 4.2.19 on 2025-04-21 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_join_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionsrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectionsrequest",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
