# Generated by Django 4.2.19 on 2025-04-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_collectionsrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookrequest',
            name='unique_open_request',
        ),
        migrations.AddConstraint(
            model_name='bookrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['denied', 'expired']), _negated=True), fields=('book', 'patron'), name='unique_open_request'),
        ),
    ]
