
# Generated by Django 4.2.19 on 2025-04-13 19:18


from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=20)),
                (
                    "isbn",
                    models.CharField(
                        help_text="Enter 13-digit ISBN: ",
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ISBN must be exactly 13 digits!",
                                regex="^\\d{13}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Checked out", "Checked out"),
                        ],
                        default="Available",
                        max_length=13,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("LikeNew", "Like New"),
                            ("Good", "Good"),
                            ("Acceptable", "Acceptable"),
                            ("Poor", "Poor"),
                        ],
                        default="Acceptable",
                        max_length=13,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Romance", "Romance"),
                            ("Adventure", "Adventure"),
                            ("Mystery", "Mystery"),
                            ("Non-fiction", "Non-fiction"),
                            ("Fantasy", "Fantasy"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Shannon Library", "Shannon Library"),
                            (
                                "Student Health and Wellness",
                                "Student Health and Wellness",
                            ),
                            ("Gibbons", "Gibbons"),
                            ("Rice Hall", "Rice Hall"),
                        ],
                        default="Shannon Library",
                        max_length=27,
                    ),
                ),
                (
                    "comments",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("description", models.TextField(default=" ", max_length=200)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                ("is_private", models.BooleanField(default=False)),
                (
                    "lender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listed_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(max_length=200)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("rating", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comms",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_collections', to=settings.AUTH_USER_MODEL)),
                ('books', models.ManyToManyField(blank=True, related_name='collections', to='catalog.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
